export const WISH_QUOTES = [
  'And here’s wishing you the very best for all the new ventures, that life has in store for you.',
  'I find my heart singing a chorus at your happy news. Good luck to you during this joyous time.',
  'Keep your best wishes, close to your heart and watch what happens.',
  'Don’t be afraid of moving forward. The future is bright.',
  'Good luck and tons of best wishes. God bless you in whatever you do. This is my heartiest wish just for you.',
  'Here’s wishing you success in everything you do. Good luck.',
  'Success comes only to those who believe in themselves and are prepared to win. Good Luck.',
  'I wish nothing but the best for you.',
  'Moving on to a new stage in life can be a challenging process. We wish you the best of luck in all of your future endeavors, you will be great.',
  'It’s kind of fun to do the impossible. All the best.',
  'Good luck to you as you move onto the next stage in your life. Without a doubt, you will continue to have success in all areas.',
  'May success be with you, always. Wishing you good luck.',
  'May you do well and come out with flying colors. All the best.',
  'May you fly high in life & success be with you always.',
  'Try a little harder to be a little better. All the best.',
  'The future is bright and beautiful. Love it, strive for it and work for it.',
  'My heart is filled with joy at the sound of your good news. Best of luck to you dear friend.',
  'Be strong as you fight your way to success, the difficulty you face is nothing compared to the joy of success.',
  'Good luck to you as you move toward the next chapter life brings your way.',
  'Good luck and tons of best wishes. God bless you in whatever you do. This is my heartiest wish just for you.',
  'If you can dream it, you can do it. Best wishes for your bright future.',
  'I wish you all the success, happiness, and joy in life.',
  'You have worked incredibly hard. Good luck. We are proud of you.',
  'Don’t look back. For a bright future is ahead of you.',
  'You have proven yourself to be a very skilled individual who has the capacity to do great things with their life. Continue to make us proud as you face new challenges and adventures.',
  'Dream Big. Sparkle More. Shine Bright.',
  'A little smile, a word of cheer, a bit of love from someone near, a little gift from one held dear, best wishes for the coming year. These make a merry Christmas. – John Greenleaf Whittier',
  'To accomplish great things, we must not only act, but also dream, not only plan but also believe, best wishes for your exam. – Ralph Chaplin',
  'Keep your best wishes and your biggest goals close to your heart and dedicate time to them every day. If you truly care about what you do and you work diligently at it, there’s almost nothing you can’t accomplish. – Melchor Lim',
  'Keep your best wishes, close to your heart and watch what happens. – Tony Deliso',
  'Luck is yours wishes are mine. Let your future always shine. Best of Luck. – Ralph Chaplin',
  'I am glad to hear that you are starting your own business after the excellent work experience. My Good Wishes are always with you. – Ralph Chaplin',
  'Best wishes to you as you progress from one stage in life to another. While this can be a difficult time, the results that you will achieve are worth all of the hard work that you will put in. – Rajesh Mankar',
  'Here is the best wish for the new year: Let there be more freedom of thought throughout the world! Fields need rain; truths need freedom of thought. – Mehmet Murat ildan',
  'You were born together, and together you shall be forevermore but let there be spaces in your togetherness. And let the winds of the heavens dance between you. – Kahlil Gibran',
  'I wish you for all your dreams of tomorrow, I wish you’re having faith they all come true. I wish you all these things–but remember, sometimes wishes and dreams are all up to you. – Ralph Chaplin',
  'I wish I had it in my power to furnish you with accommodation I should feel proud to do it, shall be happy to hear from you at anytime when you engagements will allow you an hour and remain with best wishes for yourself, family and circuit.      – John Hawley',
  'My anxious recollections, my sympathetic feeling, and my best wishes are irresistibly excited whensoever, in any country, I see an oppressed nation unfurl the banners of freedom. – George Washington',
  'Hope your burdens are feeling lighter, and each day is a little bit brighter.',
  'I am thrilled to know that luck has finally found you. Warmest wishes my friend.',
  'We dropped by to say we will miss you lots. All the best to you.',
  'I believe in you. Good Luck.',
  'May your pockets be heavy and your heart be light.',
  'May Good luck pursue you each morning and night.',
  'Sending you good luck vibes.',
  'Changing the face can change nothing, but facing the change can change everything. Good Luck.',
  'May your good luck be always good.',
  'Sending this lucky butterfly to shower you with love, luck & blessings.',
  'You have worked incredibly hard. Good luck. We are proud of you.',
  'The way in which you approach a challenge is exemplary. May you make it happen. Good Luck.',
  'May God be kind, generous and rewarding. Good Luck.',
  'As long as you have hard work in your stride good Luck will always',
  'You deserve it, go for it. Good Luck.',
  'Good luck with all your efforts. May you get what you truly deserve.',
  'My good wishes are always with you. Go for it.',
  'The road may seem rough, life may seem tough, but for a smooth sailing, my good luck wishes are enough.',
  'May the wings of the butterfly kiss the sun. And find your shoulder to light on.To bring you luck, happiness and riches. Today, tomorrow and beyond.',
  'May your troubles be less and your blessings be more. And nothing but happiness come through your door.',
  'Best of Luck for success to be there with you in every walk of life. May all the dreams that your heart hold, dear, come true. And may each day of life bring the best for you. All The Best.',
  'I want to wish you good luck in whatever you do, may you get all things new, you have done your best in case. You will definitely win the race of life so just a little strive, and you would be there. You will get your fair share so do your best you can and you will get the plan.',
  'Happiness doesn’t stay in your life for long. So when you have it, enjoy it to the fullest. Wishing you all the best.',
  'Happiness is always in your life, may God prosper happiness, wealth and good luck forever in your life.',
  'Luck is for the lazy. Success is for those who work hard.',
  'A champion is scared of losing while everyone else is scared of winning.',
  'There will be no success without hardship. All the best.',
  'Don’t tell people your dreams. Show them! Best wishes for your future.',
  'Sending well wishes and plenty of sunshine your way to brighten up your day.',
  'You are a truly talented person and I wish you well throughout your life.',
  'May you always get what you want and may you be at the right place. I wish you a very good luck for the future and may you have a wonderful life with no worries.',
  'Good Luck. Hope you enjoy your new life.',
  'The best time for new beginnings is now. All the best.',
  'Do your best. That’s all you can do!',
  'May you always walk the glorious road to success. All the best in life. May you achieve greatness and touch all your dreams.',
  'Your effort is sure to win. Keep up the spirit.',
  'Set your goals high, and don’t stop till you get there. All the best.',
  'Close your eyes and make a wish.',
  'May you get all your wishes but one, so you always have something to strive for. – An Irish Blessing',
  'The universe works in crazy ways. Your good luck will come in waves, and so does your bad, so you have to take the good with the bad and press forward. – Nick Cummins',
  'If I have to wish you something, I would have to say have a very nice day.',
  'May your pockets be heavy and your heart be light. May Good luck pursue you each morning and night.',
  'May the wings of the butterfly kiss the sun. And find your shoulder to light on. To bring you luck, happiness and riches. Today, tomorrow and beyond.',
  'The good luck you have made for yourself is an inspiration to many. May it continue throughout your life.',
  'I wish you a very happy life ahead in which you do not need to worry about anything. May you get all the thing you want in life. Best Wishes Always.',
  'If we had one wish for you on this special day it would be: May the best of your past be the worst of your future. – Catherine Pulsifer',
  'May the sun always shine on your window pane; may a rainbow be certain to follow each rain. – Irish Proverb',
  'Good luck is a residue of preparation. – Jack Youngblood',
  'To accomplish great things, we must not only act, but also dream; not only plan, but also believe. – Anatole France',
  'Here are best wishes that your profession brings satisfaction, and pride to you always.  ',
  'Best wishes that your new degree will be a source of success you so richly deserve.',
  'Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do. So throw off the bowlines. Sail away from the safe harbor. Catch the trade winds in your sails. Explore. Dream. Discover. – Mark Twain',
  'And in today already walks tomorrow. – Samuel Taylor Coleridge',
  'You are never given a wish without also being given the power to make it come true. You may have to work for it, however. – Richard Bach',
  'Fear not for the future, weep not for the past. – Percy Blythe Shelley',
  'Go confidently in the direction of your dreams. Live the life you have imagined. – Henry David Thoreau',
  'When it comes to the future, there are three kinds of people: those who let it happen, those who make it happen, and those who wonder what happened. – John M. Richardson',
  'Happy Graduation! Make a difference, live the dream, relish the adventure and stand strong.',
  'You’re off to great places! Today is your day. Your mountain is waiting. So get on your way. – Dr. Seuss',
  'We wanted to wish you well during this very special time in your life.',
  'Never doubt your abilities for a moment in life. Wish you good luck and all the best.',
  'If you can’t see the bright side of life, polish the dull side.',
  'Sending best wishes to hope to show that how much I love you.',
  'From all of us to you, we wish you well and hope that all of your dreams come true.',
  'Luck is yours, greetings are mine, you get every success and let your future always shine. Best Wishes & Greetings.',
  'Wish you the very best in everything as you deserve nothing less.',
  'Wishing your dreams begin to come true, and every tomorrow be happy for you.',
  'As you start this new journey in life, may every day hold wonderful experiences.',
  'Be brave to let go of the past. And fight for the present that you deserve. A better future is always yours.',
  'Here’s wishing you all the best for your endeavors in the coming year.',
  'Don’t stress. Do your best. Forget the rest.',
  'If you keep working as hard in the future, nothing can stop you. All the best.',
  'We wish you all the very best for your future life. May everything that you do make you happy and rise.',
  'Good luck. Hope everything turns out to be simply great for you.',
  'Only you can control your future.',
  'Every sunset gives us one day less to live! But every sunrise gives us one day more to hope. So, hope for the Best. Good Day.',
  'If all you can do is crawl, start crawling.',
  'The secret to a rich life is to have more beginnings than endings. – Dave Weinbaum',
  'Don’t be afraid to move on and start a new chapter.',
  'Do not wait until the conditions are perfect to begin. Beginning makes the conditions perfect.',
  'Don’t wait. Make memories today. Celebrate your life.',
  'Life is a great big canvas, and you should throw all the paint on it you can.',
  'Life isn’t about finding yourself. Life is about creating yourself. – George Bernard Shaw',
  'Sending you good luck vibes.',
  'Your future will always be bright when you stay focused optimistic and confident.',
  'Follow your dreams. Never say never.',
  'Smile knowing that good luck has finally found you. Wishing you plenty of joy, happiness, and health.',
  'Don’t be afraid to start over. It’s a brand new opportunity to rebuild what you truly want.',
  'Just remember – when you think all is lost, the future remains.',
  'All life is an experiment. The more experiments you make the better.',
  'I just took a trip to your future in my time machine, and it looks bright. All the best.',
  'I’m making a prediction that you are going to keep being awesome.',
  'Good seasons start with good beginnings.',
  'Take the first step in faith. You don’t have to see the whole staircase, just take the first step. – Martin Luther King, Jr.',
  'You will never win if you never begin.',
  'Start by doing what’s necessary; then do what’s possible; and suddenly you are doing the impossible.',
  'Start wherever you are and start small. All the best.',
  'So happy to hear your wonderful news. Here’s to wishing you the best of luck.',
  'May all your dreams come true.',
  'Don’t ever change. Stay as amazing as you are, my friend',
  'You will meet many people in life who will hate you much. But you have to stand strong and straight and you have to be yourself. Define yourself with how strong you stand at that time. Good luck, have a happy life.',
  'Being failure or loser is totally up to you. Just remember one thing that the failure is a defeat for the loser and it is nothing less than inspiration for the winners. Get inspired by your failure and get success next time. I wish you the best of luck and may you be a winner every time in life.',
  'Wishing you strength to face every problem, joy and happiness to enjoy your wonderful life, love to make life beautiful, talent to make life good and worth living, and a very happy life. Best of luck my dear.',
  'They say that successful people are those who dream big, but I believe that they not only believe but their actions are more important in their success. They do hard work to get their desires and to change their dreams into a reality. I wish you strength and a good luck in life.',
  'If your good luck is with you, all the good things happen to you in life. You get happiness, friends, love and success in life. Best of luck to achieve your desires.',
  'You may be hurt sometimes, you may fail and lose sometimes. You may not get what you want, but never stop thinking good and struggling. By struggles, you will get everything you want. This is the real success. I wish you good luck with your tasks.',
  'Success is never permanent and it comes to only those people who try again and who do not wait and hesitate. It comes to those people who are ready to do anything. I wish you the best of luck. May you have a successful life ahead.',
  'Success may be for some time but what you have achieved will always be yours and will stay with you forever. Work hard to achieve things, it may take your time today but you will cherish it tomorrow. Good luck to you dear.',
  'Actions are much more important than dreams in order to achieve something really great. You must have a proper plan for how to achieve it. And the most important thing is that you must believe yourself that you can do it. I wish you good luck with all the things you have to achieve.',
  'Yes, no perfect life is there. But it can be made perfect by having lots of perfect moments and celebrating them. Best of luck dear',
  'Life is not perfect but you can make it perfect yourself. All you need to make your life perfect is love, happiness, laughter and lots of luck. I wish you the best of luck for a perfect life with happiness all the way.',
  'They say that you need oxygen to live. But I believe that there are some other things without which life will be so difficult. Those important things are love, happiness and most importantly Luck. Luck is very important to survive in life. I wish you the best of luck in all your life. May you have a great life ahead.',
  'Never stop believing in yourself. Never think of quitting in life. You can do everything and you can get through every problem if you don’t quit and if you have belief in yourself. I will always be there for you to help you out whenever you need me and I will stand beside you every time. Wishing you the best of luck for the future.',
  'Be prepared for any kind of tasks every time. Always believe in yourself. If you follow these two things then you will surely get success in every field of life. I hope that you win each task and you have a very happy life. Have a best of luck in all your life.',
  'Never ever think of quitting. Think about winning and you will win for sure. Keep on running and struggling and then there is no force that can stop you from getting success in life. Have courage and belief in yourself and then go ahead and face every problem with all the courage. Then nothing can stop you from winning. Best of luck to you my friend.',
];

export const getQuote = (): string => {
  const counter = Number(localStorage.getItem('visit') || 0);

  // update for next quote
  localStorage.setItem('visit', String(counter + 1));

  return WISH_QUOTES[counter % WISH_QUOTES.length];
};
