/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RouterHistory } from "@stencil/router";
export namespace Components {
    interface AppRoot {
    }
    interface WwButton {
        "kind": 'primary' | 'secondary' | 'tertiary';
        "type": 'button' | 'submit';
    }
    interface WwCancel {
        "history": RouterHistory;
    }
    interface WwError {
    }
    interface WwHome {
    }
    interface WwQuote {
    }
    interface WwSuccess {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLWwButtonElement extends Components.WwButton, HTMLStencilElement {
    }
    var HTMLWwButtonElement: {
        prototype: HTMLWwButtonElement;
        new (): HTMLWwButtonElement;
    };
    interface HTMLWwCancelElement extends Components.WwCancel, HTMLStencilElement {
    }
    var HTMLWwCancelElement: {
        prototype: HTMLWwCancelElement;
        new (): HTMLWwCancelElement;
    };
    interface HTMLWwErrorElement extends Components.WwError, HTMLStencilElement {
    }
    var HTMLWwErrorElement: {
        prototype: HTMLWwErrorElement;
        new (): HTMLWwErrorElement;
    };
    interface HTMLWwHomeElement extends Components.WwHome, HTMLStencilElement {
    }
    var HTMLWwHomeElement: {
        prototype: HTMLWwHomeElement;
        new (): HTMLWwHomeElement;
    };
    interface HTMLWwQuoteElement extends Components.WwQuote, HTMLStencilElement {
    }
    var HTMLWwQuoteElement: {
        prototype: HTMLWwQuoteElement;
        new (): HTMLWwQuoteElement;
    };
    interface HTMLWwSuccessElement extends Components.WwSuccess, HTMLStencilElement {
    }
    var HTMLWwSuccessElement: {
        prototype: HTMLWwSuccessElement;
        new (): HTMLWwSuccessElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "ww-button": HTMLWwButtonElement;
        "ww-cancel": HTMLWwCancelElement;
        "ww-error": HTMLWwErrorElement;
        "ww-home": HTMLWwHomeElement;
        "ww-quote": HTMLWwQuoteElement;
        "ww-success": HTMLWwSuccessElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface WwButton {
        "kind"?: 'primary' | 'secondary' | 'tertiary';
        "type"?: 'button' | 'submit';
    }
    interface WwCancel {
        "history"?: RouterHistory;
    }
    interface WwError {
    }
    interface WwHome {
    }
    interface WwQuote {
    }
    interface WwSuccess {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "ww-button": WwButton;
        "ww-cancel": WwCancel;
        "ww-error": WwError;
        "ww-home": WwHome;
        "ww-quote": WwQuote;
        "ww-success": WwSuccess;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "ww-button": LocalJSX.WwButton & JSXBase.HTMLAttributes<HTMLWwButtonElement>;
            "ww-cancel": LocalJSX.WwCancel & JSXBase.HTMLAttributes<HTMLWwCancelElement>;
            "ww-error": LocalJSX.WwError & JSXBase.HTMLAttributes<HTMLWwErrorElement>;
            "ww-home": LocalJSX.WwHome & JSXBase.HTMLAttributes<HTMLWwHomeElement>;
            "ww-quote": LocalJSX.WwQuote & JSXBase.HTMLAttributes<HTMLWwQuoteElement>;
            "ww-success": LocalJSX.WwSuccess & JSXBase.HTMLAttributes<HTMLWwSuccessElement>;
        }
    }
}
